// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: proto/subnet/agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentStatus int32

const (
	AgentStatus_AGENT_STATUS_UNKNOWN   AgentStatus = 0
	AgentStatus_AGENT_STATUS_ACTIVE    AgentStatus = 1
	AgentStatus_AGENT_STATUS_INACTIVE  AgentStatus = 2
	AgentStatus_AGENT_STATUS_UNHEALTHY AgentStatus = 3
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNKNOWN",
		1: "AGENT_STATUS_ACTIVE",
		2: "AGENT_STATUS_INACTIVE",
		3: "AGENT_STATUS_UNHEALTHY",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNKNOWN":   0,
		"AGENT_STATUS_ACTIVE":    1,
		"AGENT_STATUS_INACTIVE":  2,
		"AGENT_STATUS_UNHEALTHY": 3,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_subnet_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_proto_subnet_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_subnet_agent_proto_rawDescGZIP(), []int{0}
}

// Agent represents an agent in the subnet
type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Status        AgentStatus            `protobuf:"varint,4,opt,name=status,proto3,enum=subnet.v1.AgentStatus" json:"status,omitempty"`
	LastSeen      int64                  `protobuf:"varint,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_proto_subnet_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_proto_subnet_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Agent) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Agent) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNKNOWN
}

func (x *Agent) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

var File_proto_subnet_agent_proto protoreflect.FileDescriptor

const file_proto_subnet_agent_proto_rawDesc = "" +
	"\n" +
	"\x18proto/subnet/agent.proto\x12\tsubnet.v1\"\xa4\x01\n" +
	"\x05Agent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12.\n" +
	"\x06status\x18\x04 \x01(\x0e2\x16.subnet.v1.AgentStatusR\x06status\x12\x1b\n" +
	"\tlast_seen\x18\x05 \x01(\x03R\blastSeen*w\n" +
	"\vAgentStatus\x12\x18\n" +
	"\x14AGENT_STATUS_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13AGENT_STATUS_ACTIVE\x10\x01\x12\x19\n" +
	"\x15AGENT_STATUS_INACTIVE\x10\x02\x12\x1a\n" +
	"\x16AGENT_STATUS_UNHEALTHY\x10\x03B\x18Z\x16subnet/proto/subnet;pbb\x06proto3"

var (
	file_proto_subnet_agent_proto_rawDescOnce sync.Once
	file_proto_subnet_agent_proto_rawDescData []byte
)

func file_proto_subnet_agent_proto_rawDescGZIP() []byte {
	file_proto_subnet_agent_proto_rawDescOnce.Do(func() {
		file_proto_subnet_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subnet_agent_proto_rawDesc), len(file_proto_subnet_agent_proto_rawDesc)))
	})
	return file_proto_subnet_agent_proto_rawDescData
}

var file_proto_subnet_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_subnet_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_subnet_agent_proto_goTypes = []any{
	(AgentStatus)(0), // 0: subnet.v1.AgentStatus
	(*Agent)(nil),    // 1: subnet.v1.Agent
}
var file_proto_subnet_agent_proto_depIdxs = []int32{
	0, // 0: subnet.v1.Agent.status:type_name -> subnet.v1.AgentStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_subnet_agent_proto_init() }
func file_proto_subnet_agent_proto_init() {
	if File_proto_subnet_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subnet_agent_proto_rawDesc), len(file_proto_subnet_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_subnet_agent_proto_goTypes,
		DependencyIndexes: file_proto_subnet_agent_proto_depIdxs,
		EnumInfos:         file_proto_subnet_agent_proto_enumTypes,
		MessageInfos:      file_proto_subnet_agent_proto_msgTypes,
	}.Build()
	File_proto_subnet_agent_proto = out.File
	file_proto_subnet_agent_proto_goTypes = nil
	file_proto_subnet_agent_proto_depIdxs = nil
}
