// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: proto/subnet/execution_report.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionReport_Status int32

const (
	ExecutionReport_STATUS_UNSPECIFIED ExecutionReport_Status = 0
	ExecutionReport_SUCCESS            ExecutionReport_Status = 1
	ExecutionReport_FAILED             ExecutionReport_Status = 2
	ExecutionReport_PARTIAL            ExecutionReport_Status = 3
)

// Enum value maps for ExecutionReport_Status.
var (
	ExecutionReport_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "SUCCESS",
		2: "FAILED",
		3: "PARTIAL",
	}
	ExecutionReport_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"SUCCESS":            1,
		"FAILED":             2,
		"PARTIAL":            3,
	}
)

func (x ExecutionReport_Status) Enum() *ExecutionReport_Status {
	p := new(ExecutionReport_Status)
	*p = x
	return p
}

func (x ExecutionReport_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionReport_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_subnet_execution_report_proto_enumTypes[0].Descriptor()
}

func (ExecutionReport_Status) Type() protoreflect.EnumType {
	return &file_proto_subnet_execution_report_proto_enumTypes[0]
}

func (x ExecutionReport_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionReport_Status.Descriptor instead.
func (ExecutionReport_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_subnet_execution_report_proto_rawDescGZIP(), []int{0, 0}
}

// Execution report submitted by Agent Service to Validators.
type ExecutionReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	AssignmentId  string                 `protobuf:"bytes,2,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	IntentId      string                 `protobuf:"bytes,3,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        ExecutionReport_Status `protobuf:"varint,5,opt,name=status,proto3,enum=subnet.v1.ExecutionReport_Status" json:"status,omitempty"`
	ResultData    []byte                 `protobuf:"bytes,6,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"` // opaque; recommend DA for large payloads
	Evidence      *VerificationEvidence  `protobuf:"bytes,7,opt,name=evidence,proto3" json:"evidence,omitempty"`                       // required evidence set
	Error         *ErrorInfo             `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`                             // optional
	Timestamp     int64                  `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                    // unix seconds
	Signature     []byte                 `protobuf:"bytes,10,opt,name=signature,proto3" json:"signature,omitempty"`                    // agent ECDSA signature over domain hash
	RootRef       *RootLayerRef          `protobuf:"bytes,11,opt,name=root_ref,json=rootRef,proto3" json:"root_ref,omitempty"`         // optional: root layer reference for audit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionReport) Reset() {
	*x = ExecutionReport{}
	mi := &file_proto_subnet_execution_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionReport) ProtoMessage() {}

func (x *ExecutionReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_execution_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionReport.ProtoReflect.Descriptor instead.
func (*ExecutionReport) Descriptor() ([]byte, []int) {
	return file_proto_subnet_execution_report_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ExecutionReport) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *ExecutionReport) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *ExecutionReport) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ExecutionReport) GetStatus() ExecutionReport_Status {
	if x != nil {
		return x.Status
	}
	return ExecutionReport_STATUS_UNSPECIFIED
}

func (x *ExecutionReport) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *ExecutionReport) GetEvidence() *VerificationEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *ExecutionReport) GetError() *ErrorInfo {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *ExecutionReport) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ExecutionReport) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ExecutionReport) GetRootRef() *RootLayerRef {
	if x != nil {
		return x.RootRef
	}
	return nil
}

type VerificationEvidence struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnvFingerprint []byte                 `protobuf:"bytes,1,opt,name=env_fingerprint,json=envFingerprint,proto3" json:"env_fingerprint,omitempty"` // image/wasm/code hash, version
	InputsHash     []byte                 `protobuf:"bytes,2,opt,name=inputs_hash,json=inputsHash,proto3" json:"inputs_hash,omitempty"`
	OutputsHash    []byte                 `protobuf:"bytes,3,opt,name=outputs_hash,json=outputsHash,proto3" json:"outputs_hash,omitempty"`
	TranscriptRoot []byte                 `protobuf:"bytes,4,opt,name=transcript_root,json=transcriptRoot,proto3" json:"transcript_root,omitempty"`
	ProofExec      []byte                 `protobuf:"bytes,5,opt,name=proof_exec,json=proofExec,proto3" json:"proof_exec,omitempty"` // optional, serialized proof
	ResourceUsage  *ResourceUsage         `protobuf:"bytes,6,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
	ExternalRefs   []string               `protobuf:"bytes,7,rep,name=external_refs,json=externalRefs,proto3" json:"external_refs,omitempty"` // optional references
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VerificationEvidence) Reset() {
	*x = VerificationEvidence{}
	mi := &file_proto_subnet_execution_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationEvidence) ProtoMessage() {}

func (x *VerificationEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_execution_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationEvidence.ProtoReflect.Descriptor instead.
func (*VerificationEvidence) Descriptor() ([]byte, []int) {
	return file_proto_subnet_execution_report_proto_rawDescGZIP(), []int{1}
}

func (x *VerificationEvidence) GetEnvFingerprint() []byte {
	if x != nil {
		return x.EnvFingerprint
	}
	return nil
}

func (x *VerificationEvidence) GetInputsHash() []byte {
	if x != nil {
		return x.InputsHash
	}
	return nil
}

func (x *VerificationEvidence) GetOutputsHash() []byte {
	if x != nil {
		return x.OutputsHash
	}
	return nil
}

func (x *VerificationEvidence) GetTranscriptRoot() []byte {
	if x != nil {
		return x.TranscriptRoot
	}
	return nil
}

func (x *VerificationEvidence) GetProofExec() []byte {
	if x != nil {
		return x.ProofExec
	}
	return nil
}

func (x *VerificationEvidence) GetResourceUsage() *ResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

func (x *VerificationEvidence) GetExternalRefs() []string {
	if x != nil {
		return x.ExternalRefs
	}
	return nil
}

type ResourceUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMs         uint64                 `protobuf:"varint,1,opt,name=cpu_ms,json=cpuMs,proto3" json:"cpu_ms,omitempty"`
	MemoryMb      uint64                 `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	IoOps         uint64                 `protobuf:"varint,3,opt,name=io_ops,json=ioOps,proto3" json:"io_ops,omitempty"`
	NetworkBytes  uint64                 `protobuf:"varint,4,opt,name=network_bytes,json=networkBytes,proto3" json:"network_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	mi := &file_proto_subnet_execution_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_execution_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceUsage.ProtoReflect.Descriptor instead.
func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_proto_subnet_execution_report_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceUsage) GetCpuMs() uint64 {
	if x != nil {
		return x.CpuMs
	}
	return 0
}

func (x *ResourceUsage) GetMemoryMb() uint64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ResourceUsage) GetIoOps() uint64 {
	if x != nil {
		return x.IoOps
	}
	return 0
}

func (x *ResourceUsage) GetNetworkBytes() uint64 {
	if x != nil {
		return x.NetworkBytes
	}
	return 0
}

type ErrorInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []byte                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_proto_subnet_execution_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_execution_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_proto_subnet_execution_report_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ErrorInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorInfo) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_proto_subnet_execution_report_proto protoreflect.FileDescriptor

const file_proto_subnet_execution_report_proto_rawDesc = "" +
	"\n" +
	"#proto/subnet/execution_report.proto\x12\tsubnet.v1\x1a\x19proto/subnet/report.proto\"\x88\x04\n" +
	"\x0fExecutionReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12#\n" +
	"\rassignment_id\x18\x02 \x01(\tR\fassignmentId\x12\x1b\n" +
	"\tintent_id\x18\x03 \x01(\tR\bintentId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x129\n" +
	"\x06status\x18\x05 \x01(\x0e2!.subnet.v1.ExecutionReport.StatusR\x06status\x12\x1f\n" +
	"\vresult_data\x18\x06 \x01(\fR\n" +
	"resultData\x12;\n" +
	"\bevidence\x18\a \x01(\v2\x1f.subnet.v1.VerificationEvidenceR\bevidence\x12*\n" +
	"\x05error\x18\b \x01(\v2\x14.subnet.v1.ErrorInfoR\x05error\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\n" +
	" \x01(\fR\tsignature\x122\n" +
	"\broot_ref\x18\v \x01(\v2\x17.subnet.v1.RootLayerRefR\arootRef\"F\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x02\x12\v\n" +
	"\aPARTIAL\x10\x03\"\xb1\x02\n" +
	"\x14VerificationEvidence\x12'\n" +
	"\x0fenv_fingerprint\x18\x01 \x01(\fR\x0eenvFingerprint\x12\x1f\n" +
	"\vinputs_hash\x18\x02 \x01(\fR\n" +
	"inputsHash\x12!\n" +
	"\foutputs_hash\x18\x03 \x01(\fR\voutputsHash\x12'\n" +
	"\x0ftranscript_root\x18\x04 \x01(\fR\x0etranscriptRoot\x12\x1d\n" +
	"\n" +
	"proof_exec\x18\x05 \x01(\fR\tproofExec\x12?\n" +
	"\x0eresource_usage\x18\x06 \x01(\v2\x18.subnet.v1.ResourceUsageR\rresourceUsage\x12#\n" +
	"\rexternal_refs\x18\a \x03(\tR\fexternalRefs\"\x7f\n" +
	"\rResourceUsage\x12\x15\n" +
	"\x06cpu_ms\x18\x01 \x01(\x04R\x05cpuMs\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x04R\bmemoryMb\x12\x15\n" +
	"\x06io_ops\x18\x03 \x01(\x04R\x05ioOps\x12#\n" +
	"\rnetwork_bytes\x18\x04 \x01(\x04R\fnetworkBytes\"S\n" +
	"\tErrorInfo\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\fR\adetailsB\x18Z\x16subnet/proto/subnet;pbb\x06proto3"

var (
	file_proto_subnet_execution_report_proto_rawDescOnce sync.Once
	file_proto_subnet_execution_report_proto_rawDescData []byte
)

func file_proto_subnet_execution_report_proto_rawDescGZIP() []byte {
	file_proto_subnet_execution_report_proto_rawDescOnce.Do(func() {
		file_proto_subnet_execution_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subnet_execution_report_proto_rawDesc), len(file_proto_subnet_execution_report_proto_rawDesc)))
	})
	return file_proto_subnet_execution_report_proto_rawDescData
}

var file_proto_subnet_execution_report_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_subnet_execution_report_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_subnet_execution_report_proto_goTypes = []any{
	(ExecutionReport_Status)(0),  // 0: subnet.v1.ExecutionReport.Status
	(*ExecutionReport)(nil),      // 1: subnet.v1.ExecutionReport
	(*VerificationEvidence)(nil), // 2: subnet.v1.VerificationEvidence
	(*ResourceUsage)(nil),        // 3: subnet.v1.ResourceUsage
	(*ErrorInfo)(nil),            // 4: subnet.v1.ErrorInfo
	(*RootLayerRef)(nil),         // 5: subnet.v1.RootLayerRef
}
var file_proto_subnet_execution_report_proto_depIdxs = []int32{
	0, // 0: subnet.v1.ExecutionReport.status:type_name -> subnet.v1.ExecutionReport.Status
	2, // 1: subnet.v1.ExecutionReport.evidence:type_name -> subnet.v1.VerificationEvidence
	4, // 2: subnet.v1.ExecutionReport.error:type_name -> subnet.v1.ErrorInfo
	5, // 3: subnet.v1.ExecutionReport.root_ref:type_name -> subnet.v1.RootLayerRef
	3, // 4: subnet.v1.VerificationEvidence.resource_usage:type_name -> subnet.v1.ResourceUsage
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_subnet_execution_report_proto_init() }
func file_proto_subnet_execution_report_proto_init() {
	if File_proto_subnet_execution_report_proto != nil {
		return
	}
	file_proto_subnet_report_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subnet_execution_report_proto_rawDesc), len(file_proto_subnet_execution_report_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_subnet_execution_report_proto_goTypes,
		DependencyIndexes: file_proto_subnet_execution_report_proto_depIdxs,
		EnumInfos:         file_proto_subnet_execution_report_proto_enumTypes,
		MessageInfos:      file_proto_subnet_execution_report_proto_msgTypes,
	}.Build()
	File_proto_subnet_execution_report_proto = out.File
	file_proto_subnet_execution_report_proto_goTypes = nil
	file_proto_subnet_execution_report_proto_depIdxs = nil
}
