// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: proto/subnet/registry_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_proto_subnet_registry_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_registry_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_subnet_registry_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAgentRequest) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_proto_subnet_registry_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_registry_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_subnet_registry_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnregisterAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentRequest) Reset() {
	*x = UnregisterAgentRequest{}
	mi := &file_proto_subnet_registry_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentRequest) ProtoMessage() {}

func (x *UnregisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_registry_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentRequest.ProtoReflect.Descriptor instead.
func (*UnregisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_subnet_registry_service_proto_rawDescGZIP(), []int{2}
}

func (x *UnregisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type UnregisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterAgentResponse) Reset() {
	*x = UnregisterAgentResponse{}
	mi := &file_proto_subnet_registry_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAgentResponse) ProtoMessage() {}

func (x *UnregisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_registry_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAgentResponse.ProtoReflect.Descriptor instead.
func (*UnregisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_subnet_registry_service_proto_rawDescGZIP(), []int{3}
}

func (x *UnregisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnregisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DiscoverAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []string               `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverAgentsRequest) Reset() {
	*x = DiscoverAgentsRequest{}
	mi := &file_proto_subnet_registry_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverAgentsRequest) ProtoMessage() {}

func (x *DiscoverAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_registry_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverAgentsRequest.ProtoReflect.Descriptor instead.
func (*DiscoverAgentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_subnet_registry_service_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverAgentsRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type DiscoverAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverAgentsResponse) Reset() {
	*x = DiscoverAgentsResponse{}
	mi := &file_proto_subnet_registry_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverAgentsResponse) ProtoMessage() {}

func (x *DiscoverAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_registry_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverAgentsResponse.ProtoReflect.Descriptor instead.
func (*DiscoverAgentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_subnet_registry_service_proto_rawDescGZIP(), []int{5}
}

func (x *DiscoverAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        AgentStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=subnet.v1.AgentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_subnet_registry_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_registry_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_subnet_registry_service_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNKNOWN
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_subnet_registry_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_registry_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_subnet_registry_service_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_proto_subnet_registry_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_registry_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_subnet_registry_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_proto_subnet_registry_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_registry_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_proto_subnet_registry_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type ListAgentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filters
	Capabilities  []string    `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Status        AgentStatus `protobuf:"varint,2,opt,name=status,proto3,enum=subnet.v1.AgentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_proto_subnet_registry_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_registry_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_subnet_registry_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListAgentsRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ListAgentsRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNKNOWN
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_proto_subnet_registry_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_registry_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_subnet_registry_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_proto_subnet_registry_service_proto protoreflect.FileDescriptor

const file_proto_subnet_registry_service_proto_rawDesc = "" +
	"\n" +
	"#proto/subnet/registry_service.proto\x12\tsubnet.v1\x1a\x18proto/subnet/agent.proto\">\n" +
	"\x14RegisterAgentRequest\x12&\n" +
	"\x05agent\x18\x01 \x01(\v2\x10.subnet.v1.AgentR\x05agent\"K\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"3\n" +
	"\x16UnregisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"M\n" +
	"\x17UnregisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\x15DiscoverAgentsRequest\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\"B\n" +
	"\x16DiscoverAgentsResponse\x12(\n" +
	"\x06agents\x18\x01 \x03(\v2\x10.subnet.v1.AgentR\x06agents\"]\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.subnet.v1.AgentStatusR\x06status\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\":\n" +
	"\x10GetAgentResponse\x12&\n" +
	"\x05agent\x18\x01 \x01(\v2\x10.subnet.v1.AgentR\x05agent\"g\n" +
	"\x11ListAgentsRequest\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.subnet.v1.AgentStatusR\x06status\"T\n" +
	"\x12ListAgentsResponse\x12(\n" +
	"\x06agents\x18\x01 \x03(\v2\x10.subnet.v1.AgentR\x06agents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xee\x03\n" +
	"\x0fRegistryService\x12R\n" +
	"\rRegisterAgent\x12\x1f.subnet.v1.RegisterAgentRequest\x1a .subnet.v1.RegisterAgentResponse\x12X\n" +
	"\x0fUnregisterAgent\x12!.subnet.v1.UnregisterAgentRequest\x1a\".subnet.v1.UnregisterAgentResponse\x12U\n" +
	"\x0eDiscoverAgents\x12 .subnet.v1.DiscoverAgentsRequest\x1a!.subnet.v1.DiscoverAgentsResponse\x12F\n" +
	"\tHeartbeat\x12\x1b.subnet.v1.HeartbeatRequest\x1a\x1c.subnet.v1.HeartbeatResponse\x12C\n" +
	"\bGetAgent\x12\x1a.subnet.v1.GetAgentRequest\x1a\x1b.subnet.v1.GetAgentResponse\x12I\n" +
	"\n" +
	"ListAgents\x12\x1c.subnet.v1.ListAgentsRequest\x1a\x1d.subnet.v1.ListAgentsResponseB\x18Z\x16subnet/proto/subnet;pbb\x06proto3"

var (
	file_proto_subnet_registry_service_proto_rawDescOnce sync.Once
	file_proto_subnet_registry_service_proto_rawDescData []byte
)

func file_proto_subnet_registry_service_proto_rawDescGZIP() []byte {
	file_proto_subnet_registry_service_proto_rawDescOnce.Do(func() {
		file_proto_subnet_registry_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subnet_registry_service_proto_rawDesc), len(file_proto_subnet_registry_service_proto_rawDesc)))
	})
	return file_proto_subnet_registry_service_proto_rawDescData
}

var file_proto_subnet_registry_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_subnet_registry_service_proto_goTypes = []any{
	(*RegisterAgentRequest)(nil),    // 0: subnet.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),   // 1: subnet.v1.RegisterAgentResponse
	(*UnregisterAgentRequest)(nil),  // 2: subnet.v1.UnregisterAgentRequest
	(*UnregisterAgentResponse)(nil), // 3: subnet.v1.UnregisterAgentResponse
	(*DiscoverAgentsRequest)(nil),   // 4: subnet.v1.DiscoverAgentsRequest
	(*DiscoverAgentsResponse)(nil),  // 5: subnet.v1.DiscoverAgentsResponse
	(*HeartbeatRequest)(nil),        // 6: subnet.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 7: subnet.v1.HeartbeatResponse
	(*GetAgentRequest)(nil),         // 8: subnet.v1.GetAgentRequest
	(*GetAgentResponse)(nil),        // 9: subnet.v1.GetAgentResponse
	(*ListAgentsRequest)(nil),       // 10: subnet.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),      // 11: subnet.v1.ListAgentsResponse
	(*Agent)(nil),                   // 12: subnet.v1.Agent
	(AgentStatus)(0),                // 13: subnet.v1.AgentStatus
}
var file_proto_subnet_registry_service_proto_depIdxs = []int32{
	12, // 0: subnet.v1.RegisterAgentRequest.agent:type_name -> subnet.v1.Agent
	12, // 1: subnet.v1.DiscoverAgentsResponse.agents:type_name -> subnet.v1.Agent
	13, // 2: subnet.v1.HeartbeatRequest.status:type_name -> subnet.v1.AgentStatus
	12, // 3: subnet.v1.GetAgentResponse.agent:type_name -> subnet.v1.Agent
	13, // 4: subnet.v1.ListAgentsRequest.status:type_name -> subnet.v1.AgentStatus
	12, // 5: subnet.v1.ListAgentsResponse.agents:type_name -> subnet.v1.Agent
	0,  // 6: subnet.v1.RegistryService.RegisterAgent:input_type -> subnet.v1.RegisterAgentRequest
	2,  // 7: subnet.v1.RegistryService.UnregisterAgent:input_type -> subnet.v1.UnregisterAgentRequest
	4,  // 8: subnet.v1.RegistryService.DiscoverAgents:input_type -> subnet.v1.DiscoverAgentsRequest
	6,  // 9: subnet.v1.RegistryService.Heartbeat:input_type -> subnet.v1.HeartbeatRequest
	8,  // 10: subnet.v1.RegistryService.GetAgent:input_type -> subnet.v1.GetAgentRequest
	10, // 11: subnet.v1.RegistryService.ListAgents:input_type -> subnet.v1.ListAgentsRequest
	1,  // 12: subnet.v1.RegistryService.RegisterAgent:output_type -> subnet.v1.RegisterAgentResponse
	3,  // 13: subnet.v1.RegistryService.UnregisterAgent:output_type -> subnet.v1.UnregisterAgentResponse
	5,  // 14: subnet.v1.RegistryService.DiscoverAgents:output_type -> subnet.v1.DiscoverAgentsResponse
	7,  // 15: subnet.v1.RegistryService.Heartbeat:output_type -> subnet.v1.HeartbeatResponse
	9,  // 16: subnet.v1.RegistryService.GetAgent:output_type -> subnet.v1.GetAgentResponse
	11, // 17: subnet.v1.RegistryService.ListAgents:output_type -> subnet.v1.ListAgentsResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_subnet_registry_service_proto_init() }
func file_proto_subnet_registry_service_proto_init() {
	if File_proto_subnet_registry_service_proto != nil {
		return
	}
	file_proto_subnet_agent_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subnet_registry_service_proto_rawDesc), len(file_proto_subnet_registry_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subnet_registry_service_proto_goTypes,
		DependencyIndexes: file_proto_subnet_registry_service_proto_depIdxs,
		MessageInfos:      file_proto_subnet_registry_service_proto_msgTypes,
	}.Build()
	File_proto_subnet_registry_service_proto = out.File
	file_proto_subnet_registry_service_proto_goTypes = nil
	file_proto_subnet_registry_service_proto_depIdxs = nil
}
