// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.25.3
// source: proto/subnet/report.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RootLayerRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Root          []byte                 `protobuf:"bytes,2,opt,name=root,proto3" json:"root,omitempty"`   // root hash
	Proof         []byte                 `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootLayerRef) Reset() {
	*x = RootLayerRef{}
	mi := &file_proto_subnet_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootLayerRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootLayerRef) ProtoMessage() {}

func (x *RootLayerRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootLayerRef.ProtoReflect.Descriptor instead.
func (*RootLayerRef) Descriptor() ([]byte, []int) {
	return file_proto_subnet_report_proto_rawDescGZIP(), []int{0}
}

func (x *RootLayerRef) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *RootLayerRef) GetRoot() []byte {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *RootLayerRef) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

type Report struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: use ExecutionReport in execution_report.proto
	IntentId   string        `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	RootRef    *RootLayerRef `protobuf:"bytes,3,opt,name=root_ref,json=rootRef,proto3" json:"root_ref,omitempty"`
	ExecutedAt int64         `protobuf:"varint,4,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	ReceivedTs int64         `protobuf:"varint,5,opt,name=received_ts,json=receivedTs,proto3" json:"received_ts,omitempty"`
	// Agent related (forward compatible)
	AgentId         string `protobuf:"bytes,10,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentEndpoint   string `protobuf:"bytes,11,opt,name=agent_endpoint,json=agentEndpoint,proto3" json:"agent_endpoint,omitempty"`
	EnvFingerprint  []byte `protobuf:"bytes,12,opt,name=env_fingerprint,json=envFingerprint,proto3" json:"env_fingerprint,omitempty"`
	ResultHash      []byte `protobuf:"bytes,13,opt,name=result_hash,json=resultHash,proto3" json:"result_hash,omitempty"`
	ResultUri       string `protobuf:"bytes,14,opt,name=result_uri,json=resultUri,proto3" json:"result_uri,omitempty"`
	ProofExec       []byte `protobuf:"bytes,15,opt,name=proof_exec,json=proofExec,proto3" json:"proof_exec,omitempty"`
	ConfidenceScore uint32 `protobuf:"varint,16,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	CostEstimate    uint64 `protobuf:"varint,17,opt,name=cost_estimate,json=costEstimate,proto3" json:"cost_estimate,omitempty"`
	ValidatorHints  []byte `protobuf:"bytes,18,opt,name=validator_hints,json=validatorHints,proto3" json:"validator_hints,omitempty"`
	AssignmentId    string `protobuf:"bytes,19,opt,name=assignment_id,json=assignmentId,proto3" json:"assignment_id,omitempty"`
	ResultData      []byte `protobuf:"bytes,20,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	AgentSignature  []byte `protobuf:"bytes,21,opt,name=agent_signature,json=agentSignature,proto3" json:"agent_signature,omitempty"`
	AgentPubkey     []byte `protobuf:"bytes,22,opt,name=agent_pubkey,json=agentPubkey,proto3" json:"agent_pubkey,omitempty"`
	AgentNonce      uint64 `protobuf:"varint,23,opt,name=agent_nonce,json=agentNonce,proto3" json:"agent_nonce,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_proto_subnet_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_proto_subnet_report_proto_rawDescGZIP(), []int{1}
}

func (x *Report) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *Report) GetRootRef() *RootLayerRef {
	if x != nil {
		return x.RootRef
	}
	return nil
}

func (x *Report) GetExecutedAt() int64 {
	if x != nil {
		return x.ExecutedAt
	}
	return 0
}

func (x *Report) GetReceivedTs() int64 {
	if x != nil {
		return x.ReceivedTs
	}
	return 0
}

func (x *Report) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Report) GetAgentEndpoint() string {
	if x != nil {
		return x.AgentEndpoint
	}
	return ""
}

func (x *Report) GetEnvFingerprint() []byte {
	if x != nil {
		return x.EnvFingerprint
	}
	return nil
}

func (x *Report) GetResultHash() []byte {
	if x != nil {
		return x.ResultHash
	}
	return nil
}

func (x *Report) GetResultUri() string {
	if x != nil {
		return x.ResultUri
	}
	return ""
}

func (x *Report) GetProofExec() []byte {
	if x != nil {
		return x.ProofExec
	}
	return nil
}

func (x *Report) GetConfidenceScore() uint32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *Report) GetCostEstimate() uint64 {
	if x != nil {
		return x.CostEstimate
	}
	return 0
}

func (x *Report) GetValidatorHints() []byte {
	if x != nil {
		return x.ValidatorHints
	}
	return nil
}

func (x *Report) GetAssignmentId() string {
	if x != nil {
		return x.AssignmentId
	}
	return ""
}

func (x *Report) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *Report) GetAgentSignature() []byte {
	if x != nil {
		return x.AgentSignature
	}
	return nil
}

func (x *Report) GetAgentPubkey() []byte {
	if x != nil {
		return x.AgentPubkey
	}
	return nil
}

func (x *Report) GetAgentNonce() uint64 {
	if x != nil {
		return x.AgentNonce
	}
	return 0
}

type Receipt struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	IntentId    string                 `protobuf:"bytes,1,opt,name=intent_id,json=intentId,proto3" json:"intent_id,omitempty"`
	ValidatorId string                 `protobuf:"bytes,2,opt,name=validator_id,json=validatorId,proto3" json:"validator_id,omitempty"`
	ReceivedTs  int64                  `protobuf:"varint,3,opt,name=received_ts,json=receivedTs,proto3" json:"received_ts,omitempty"`
	Status      string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // accepted/rejected
	ScoreHint   uint32                 `protobuf:"varint,5,opt,name=score_hint,json=scoreHint,proto3" json:"score_hint,omitempty"`
	// Extensions for execution report flow (optional)
	ReportId      string `protobuf:"bytes,6,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"` // if available
	Phase         string `protobuf:"bytes,7,opt,name=phase,proto3" json:"phase,omitempty"`                       // RECEIVED/VALIDATING/VERIFIED/REJECTED (optional)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_proto_subnet_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subnet_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_proto_subnet_report_proto_rawDescGZIP(), []int{2}
}

func (x *Receipt) GetIntentId() string {
	if x != nil {
		return x.IntentId
	}
	return ""
}

func (x *Receipt) GetValidatorId() string {
	if x != nil {
		return x.ValidatorId
	}
	return ""
}

func (x *Receipt) GetReceivedTs() int64 {
	if x != nil {
		return x.ReceivedTs
	}
	return 0
}

func (x *Receipt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Receipt) GetScoreHint() uint32 {
	if x != nil {
		return x.ScoreHint
	}
	return 0
}

func (x *Receipt) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *Receipt) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

var File_proto_subnet_report_proto protoreflect.FileDescriptor

const file_proto_subnet_report_proto_rawDesc = "" +
	"\n" +
	"\x19proto/subnet/report.proto\x12\tsubnet.v1\"P\n" +
	"\fRootLayerRef\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x12\n" +
	"\x04root\x18\x02 \x01(\fR\x04root\x12\x14\n" +
	"\x05proof\x18\x03 \x01(\fR\x05proof\"\xa9\x05\n" +
	"\x06Report\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x122\n" +
	"\broot_ref\x18\x03 \x01(\v2\x17.subnet.v1.RootLayerRefR\arootRef\x12\x1f\n" +
	"\vexecuted_at\x18\x04 \x01(\x03R\n" +
	"executedAt\x12\x1f\n" +
	"\vreceived_ts\x18\x05 \x01(\x03R\n" +
	"receivedTs\x12\x19\n" +
	"\bagent_id\x18\n" +
	" \x01(\tR\aagentId\x12%\n" +
	"\x0eagent_endpoint\x18\v \x01(\tR\ragentEndpoint\x12'\n" +
	"\x0fenv_fingerprint\x18\f \x01(\fR\x0eenvFingerprint\x12\x1f\n" +
	"\vresult_hash\x18\r \x01(\fR\n" +
	"resultHash\x12\x1d\n" +
	"\n" +
	"result_uri\x18\x0e \x01(\tR\tresultUri\x12\x1d\n" +
	"\n" +
	"proof_exec\x18\x0f \x01(\fR\tproofExec\x12)\n" +
	"\x10confidence_score\x18\x10 \x01(\rR\x0fconfidenceScore\x12#\n" +
	"\rcost_estimate\x18\x11 \x01(\x04R\fcostEstimate\x12'\n" +
	"\x0fvalidator_hints\x18\x12 \x01(\fR\x0evalidatorHints\x12#\n" +
	"\rassignment_id\x18\x13 \x01(\tR\fassignmentId\x12\x1f\n" +
	"\vresult_data\x18\x14 \x01(\fR\n" +
	"resultData\x12'\n" +
	"\x0fagent_signature\x18\x15 \x01(\fR\x0eagentSignature\x12!\n" +
	"\fagent_pubkey\x18\x16 \x01(\fR\vagentPubkey\x12\x1f\n" +
	"\vagent_nonce\x18\x17 \x01(\x04R\n" +
	"agentNonceJ\x04\b\x02\x10\x03J\x04\b\x06\x10\aJ\x04\b\a\x10\bJ\x04\b\b\x10\t\"\xd4\x01\n" +
	"\aReceipt\x12\x1b\n" +
	"\tintent_id\x18\x01 \x01(\tR\bintentId\x12!\n" +
	"\fvalidator_id\x18\x02 \x01(\tR\vvalidatorId\x12\x1f\n" +
	"\vreceived_ts\x18\x03 \x01(\x03R\n" +
	"receivedTs\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"score_hint\x18\x05 \x01(\rR\tscoreHint\x12\x1b\n" +
	"\treport_id\x18\x06 \x01(\tR\breportId\x12\x14\n" +
	"\x05phase\x18\a \x01(\tR\x05phaseB\x18Z\x16subnet/proto/subnet;pbb\x06proto3"

var (
	file_proto_subnet_report_proto_rawDescOnce sync.Once
	file_proto_subnet_report_proto_rawDescData []byte
)

func file_proto_subnet_report_proto_rawDescGZIP() []byte {
	file_proto_subnet_report_proto_rawDescOnce.Do(func() {
		file_proto_subnet_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subnet_report_proto_rawDesc), len(file_proto_subnet_report_proto_rawDesc)))
	})
	return file_proto_subnet_report_proto_rawDescData
}

var file_proto_subnet_report_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_subnet_report_proto_goTypes = []any{
	(*RootLayerRef)(nil), // 0: subnet.v1.RootLayerRef
	(*Report)(nil),       // 1: subnet.v1.Report
	(*Receipt)(nil),      // 2: subnet.v1.Receipt
}
var file_proto_subnet_report_proto_depIdxs = []int32{
	0, // 0: subnet.v1.Report.root_ref:type_name -> subnet.v1.RootLayerRef
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_subnet_report_proto_init() }
func file_proto_subnet_report_proto_init() {
	if File_proto_subnet_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subnet_report_proto_rawDesc), len(file_proto_subnet_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_subnet_report_proto_goTypes,
		DependencyIndexes: file_proto_subnet_report_proto_depIdxs,
		MessageInfos:      file_proto_subnet_report_proto_msgTypes,
	}.Build()
	File_proto_subnet_report_proto = out.File
	file_proto_subnet_report_proto_goTypes = nil
	file_proto_subnet_report_proto_depIdxs = nil
}
