// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/subnet/validation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ValidationService_GetValidationPolicy_FullMethodName    = "/subnet.v1.ValidationService/GetValidationPolicy"
	ValidationService_GetVerificationRecords_FullMethodName = "/subnet.v1.ValidationService/GetVerificationRecords"
)

// ValidationServiceClient is the client API for ValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ValidationServiceClient interface {
	GetValidationPolicy(ctx context.Context, in *PolicyQuery, opts ...grpc.CallOption) (*ValidationPolicy, error)
	GetVerificationRecords(ctx context.Context, in *VerificationQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VerificationRecord], error)
}

type validationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewValidationServiceClient(cc grpc.ClientConnInterface) ValidationServiceClient {
	return &validationServiceClient{cc}
}

func (c *validationServiceClient) GetValidationPolicy(ctx context.Context, in *PolicyQuery, opts ...grpc.CallOption) (*ValidationPolicy, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationPolicy)
	err := c.cc.Invoke(ctx, ValidationService_GetValidationPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *validationServiceClient) GetVerificationRecords(ctx context.Context, in *VerificationQuery, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VerificationRecord], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ValidationService_ServiceDesc.Streams[0], ValidationService_GetVerificationRecords_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VerificationQuery, VerificationRecord]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ValidationService_GetVerificationRecordsClient = grpc.ServerStreamingClient[VerificationRecord]

// ValidationServiceServer is the server API for ValidationService service.
// All implementations must embed UnimplementedValidationServiceServer
// for forward compatibility.
type ValidationServiceServer interface {
	GetValidationPolicy(context.Context, *PolicyQuery) (*ValidationPolicy, error)
	GetVerificationRecords(*VerificationQuery, grpc.ServerStreamingServer[VerificationRecord]) error
	mustEmbedUnimplementedValidationServiceServer()
}

// UnimplementedValidationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedValidationServiceServer struct{}

func (UnimplementedValidationServiceServer) GetValidationPolicy(context.Context, *PolicyQuery) (*ValidationPolicy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValidationPolicy not implemented")
}
func (UnimplementedValidationServiceServer) GetVerificationRecords(*VerificationQuery, grpc.ServerStreamingServer[VerificationRecord]) error {
	return status.Errorf(codes.Unimplemented, "method GetVerificationRecords not implemented")
}
func (UnimplementedValidationServiceServer) mustEmbedUnimplementedValidationServiceServer() {}
func (UnimplementedValidationServiceServer) testEmbeddedByValue()                           {}

// UnsafeValidationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ValidationServiceServer will
// result in compilation errors.
type UnsafeValidationServiceServer interface {
	mustEmbedUnimplementedValidationServiceServer()
}

func RegisterValidationServiceServer(s grpc.ServiceRegistrar, srv ValidationServiceServer) {
	// If the following call pancis, it indicates UnimplementedValidationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ValidationService_ServiceDesc, srv)
}

func _ValidationService_GetValidationPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PolicyQuery)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ValidationServiceServer).GetValidationPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ValidationService_GetValidationPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ValidationServiceServer).GetValidationPolicy(ctx, req.(*PolicyQuery))
	}
	return interceptor(ctx, in, info, handler)
}

func _ValidationService_GetVerificationRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VerificationQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ValidationServiceServer).GetVerificationRecords(m, &grpc.GenericServerStream[VerificationQuery, VerificationRecord]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ValidationService_GetVerificationRecordsServer = grpc.ServerStreamingServer[VerificationRecord]

// ValidationService_ServiceDesc is the grpc.ServiceDesc for ValidationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ValidationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subnet.v1.ValidationService",
	HandlerType: (*ValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValidationPolicy",
			Handler:    _ValidationService_GetValidationPolicy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetVerificationRecords",
			Handler:       _ValidationService_GetVerificationRecords_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/subnet/validation.proto",
}
