# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: subnet/registry_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'subnet/registry_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from subnet_sdk.proto.subnet import agent_pb2 as subnet_dot_agent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsubnet/registry_service.proto\x12\tsubnet.v1\x1a\x12subnet/agent.proto\"7\n\x14RegisterAgentRequest\x12\x1f\n\x05\x61gent\x18\x01 \x01(\x0b\x32\x10.subnet.v1.Agent\"9\n\x15RegisterAgentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\x16UnregisterAgentRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\";\n\x17UnregisterAgentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\x15\x44iscoverAgentsRequest\x12\x14\n\x0c\x63\x61pabilities\x18\x01 \x03(\t\":\n\x16\x44iscoverAgentsResponse\x12 \n\x06\x61gents\x18\x01 \x03(\x0b\x32\x10.subnet.v1.Agent\"L\n\x10HeartbeatRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12&\n\x06status\x18\x02 \x01(\x0e\x32\x16.subnet.v1.AgentStatus\"5\n\x11HeartbeatResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x0fGetAgentRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"3\n\x10GetAgentResponse\x12\x1f\n\x05\x61gent\x18\x01 \x01(\x0b\x32\x10.subnet.v1.Agent\"Q\n\x11ListAgentsRequest\x12\x14\n\x0c\x63\x61pabilities\x18\x01 \x03(\t\x12&\n\x06status\x18\x02 \x01(\x0e\x32\x16.subnet.v1.AgentStatus\"E\n\x12ListAgentsResponse\x12 \n\x06\x61gents\x18\x01 \x03(\x0b\x32\x10.subnet.v1.Agent\x12\r\n\x05total\x18\x02 \x01(\x05\x32\xee\x03\n\x0fRegistryService\x12R\n\rRegisterAgent\x12\x1f.subnet.v1.RegisterAgentRequest\x1a .subnet.v1.RegisterAgentResponse\x12X\n\x0fUnregisterAgent\x12!.subnet.v1.UnregisterAgentRequest\x1a\".subnet.v1.UnregisterAgentResponse\x12U\n\x0e\x44iscoverAgents\x12 .subnet.v1.DiscoverAgentsRequest\x1a!.subnet.v1.DiscoverAgentsResponse\x12\x46\n\tHeartbeat\x12\x1b.subnet.v1.HeartbeatRequest\x1a\x1c.subnet.v1.HeartbeatResponse\x12\x43\n\x08GetAgent\x12\x1a.subnet.v1.GetAgentRequest\x1a\x1b.subnet.v1.GetAgentResponse\x12I\n\nListAgents\x12\x1c.subnet.v1.ListAgentsRequest\x1a\x1d.subnet.v1.ListAgentsResponseB\x18Z\x16subnet/proto/subnet;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'subnet.registry_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026subnet/proto/subnet;pb'
  _globals['_REGISTERAGENTREQUEST']._serialized_start=64
  _globals['_REGISTERAGENTREQUEST']._serialized_end=119
  _globals['_REGISTERAGENTRESPONSE']._serialized_start=121
  _globals['_REGISTERAGENTRESPONSE']._serialized_end=178
  _globals['_UNREGISTERAGENTREQUEST']._serialized_start=180
  _globals['_UNREGISTERAGENTREQUEST']._serialized_end=222
  _globals['_UNREGISTERAGENTRESPONSE']._serialized_start=224
  _globals['_UNREGISTERAGENTRESPONSE']._serialized_end=283
  _globals['_DISCOVERAGENTSREQUEST']._serialized_start=285
  _globals['_DISCOVERAGENTSREQUEST']._serialized_end=330
  _globals['_DISCOVERAGENTSRESPONSE']._serialized_start=332
  _globals['_DISCOVERAGENTSRESPONSE']._serialized_end=390
  _globals['_HEARTBEATREQUEST']._serialized_start=392
  _globals['_HEARTBEATREQUEST']._serialized_end=468
  _globals['_HEARTBEATRESPONSE']._serialized_start=470
  _globals['_HEARTBEATRESPONSE']._serialized_end=523
  _globals['_GETAGENTREQUEST']._serialized_start=525
  _globals['_GETAGENTREQUEST']._serialized_end=560
  _globals['_GETAGENTRESPONSE']._serialized_start=562
  _globals['_GETAGENTRESPONSE']._serialized_end=613
  _globals['_LISTAGENTSREQUEST']._serialized_start=615
  _globals['_LISTAGENTSREQUEST']._serialized_end=696
  _globals['_LISTAGENTSRESPONSE']._serialized_start=698
  _globals['_LISTAGENTSRESPONSE']._serialized_end=767
  _globals['_REGISTRYSERVICE']._serialized_start=770
  _globals['_REGISTRYSERVICE']._serialized_end=1264
# @@protoc_insertion_point(module_scope)
