# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from subnet_sdk.proto.subnet import registry_service_pb2 as subnet_dot_registry__service__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in subnet/registry_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RegistryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/subnet.v1.RegistryService/RegisterAgent',
                request_serializer=subnet_dot_registry__service__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=subnet_dot_registry__service__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.UnregisterAgent = channel.unary_unary(
                '/subnet.v1.RegistryService/UnregisterAgent',
                request_serializer=subnet_dot_registry__service__pb2.UnregisterAgentRequest.SerializeToString,
                response_deserializer=subnet_dot_registry__service__pb2.UnregisterAgentResponse.FromString,
                _registered_method=True)
        self.DiscoverAgents = channel.unary_unary(
                '/subnet.v1.RegistryService/DiscoverAgents',
                request_serializer=subnet_dot_registry__service__pb2.DiscoverAgentsRequest.SerializeToString,
                response_deserializer=subnet_dot_registry__service__pb2.DiscoverAgentsResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/subnet.v1.RegistryService/Heartbeat',
                request_serializer=subnet_dot_registry__service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=subnet_dot_registry__service__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/subnet.v1.RegistryService/GetAgent',
                request_serializer=subnet_dot_registry__service__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=subnet_dot_registry__service__pb2.GetAgentResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/subnet.v1.RegistryService/ListAgents',
                request_serializer=subnet_dot_registry__service__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=subnet_dot_registry__service__pb2.ListAgentsResponse.FromString,
                _registered_method=True)


class RegistryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=subnet_dot_registry__service__pb2.RegisterAgentRequest.FromString,
                    response_serializer=subnet_dot_registry__service__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'UnregisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterAgent,
                    request_deserializer=subnet_dot_registry__service__pb2.UnregisterAgentRequest.FromString,
                    response_serializer=subnet_dot_registry__service__pb2.UnregisterAgentResponse.SerializeToString,
            ),
            'DiscoverAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverAgents,
                    request_deserializer=subnet_dot_registry__service__pb2.DiscoverAgentsRequest.FromString,
                    response_serializer=subnet_dot_registry__service__pb2.DiscoverAgentsResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=subnet_dot_registry__service__pb2.HeartbeatRequest.FromString,
                    response_serializer=subnet_dot_registry__service__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=subnet_dot_registry__service__pb2.GetAgentRequest.FromString,
                    response_serializer=subnet_dot_registry__service__pb2.GetAgentResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=subnet_dot_registry__service__pb2.ListAgentsRequest.FromString,
                    response_serializer=subnet_dot_registry__service__pb2.ListAgentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'subnet.v1.RegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('subnet.v1.RegistryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RegistryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/subnet.v1.RegistryService/RegisterAgent',
            subnet_dot_registry__service__pb2.RegisterAgentRequest.SerializeToString,
            subnet_dot_registry__service__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/subnet.v1.RegistryService/UnregisterAgent',
            subnet_dot_registry__service__pb2.UnregisterAgentRequest.SerializeToString,
            subnet_dot_registry__service__pb2.UnregisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/subnet.v1.RegistryService/DiscoverAgents',
            subnet_dot_registry__service__pb2.DiscoverAgentsRequest.SerializeToString,
            subnet_dot_registry__service__pb2.DiscoverAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/subnet.v1.RegistryService/Heartbeat',
            subnet_dot_registry__service__pb2.HeartbeatRequest.SerializeToString,
            subnet_dot_registry__service__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/subnet.v1.RegistryService/GetAgent',
            subnet_dot_registry__service__pb2.GetAgentRequest.SerializeToString,
            subnet_dot_registry__service__pb2.GetAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/subnet.v1.RegistryService/ListAgents',
            subnet_dot_registry__service__pb2.ListAgentsRequest.SerializeToString,
            subnet_dot_registry__service__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
